Algoritmo "Questao_03"
// Disciplina :  Algoritimos e Programação I
// Professor : Arlino Henrique Magalhães de Araújo
// Aluno : Rogério de Lima Sousa
// Disponível no repositório do aluno:
// https://github.com/rogeriothe/algoritimo1/tree/master/exercicio_avaliativo
Var
   num: inteiro
Inicio

   escreval("Digite um numero:")
   leia(num)
   se num % 3 = 0 entao
      escreva("Multiplo de 3(tres)")
   senao
      escreva("Nao e multiplo de 3(tres)")
   fimse
Fimalgoritmo