Algoritmo "Questao_02"
// Disciplina :  Algoritimos e Programação I
// Professor : Arlino Henrique Magalhães de Araújo
// Aluno : Rogério de Lima Sousa
Var
   a, b, c, x, fx: Real

Inicio
    escreval("Digite o valor de a: ")
    leia(a)
    escreval("Digite o valor de b: ")
    leia(b)
    escreval("Digite o valor de c: ")
    leia(c)
    escreval("Digite o valor de x: ")
    leia(x)

    fx <- a*x*x + b*x + c
    escreval("A funcao f(", x,") = ", fx)

Fimalgoritmo